accessControl:
  enabled: false
api:
  key: B98B2340FAE64A6B96BDDFC9166E1AF3
plugins:
  announcements:
    _config_version: 1
    channels:
      _blog:
        read_until: 1551867600
      _important:
        read_until: 1521111600
      _octopi:
        read_until: 1549966200
      _plugins:
        read_until: 1551657600
      _releases:
        read_until: 1544449800
  discovery:
    upnpUuid: 8177d9dc-adfd-481d-b020-594c148a8c96
  softwareupdate:
    _config_version: 6
    check_providers:
      discordremote: discordremote
  tracking:
    enabled: false
printerProfiles:
  default: _default
server:
  commands:
    serverRestartCommand: pig
    systemRestartCommand: ashgas
  firstRun: false
  onlineCheck:
    enabled: false
  pluginBlacklist:
    enabled: false
  secretKey: BADxdaCrABj1ObYQe1OsBUvmqUsE8rck
  seenWizards:
    corewizard: 3
    cura: null
    tracking: null
devel:
  virtualPrinter:
    enabled: true
